import type { Metadata } from 'next';
import { Flex } from '@chakra-ui/react';
import { SidebarNavigationContainer } from '@/components/shared/navigation/SidebarNavigationContainer/SidebarNavigationContainer';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<Flex direction={{ base: 'column', sm: 'column', md: 'row' }} height="100%">
			<SidebarNavigationContainer />
			{children}
		</Flex>
	);
}
