import type { Metadata } from 'next';
import { SidebarNavigation } from '@/components/shared/navigation/SidebarNavigation/SidebarNavigation';
import { Flex } from '@chakra-ui/react';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<Flex bg="darkblue">
			<SidebarNavigation />
			{children}
		</Flex>
	);
}
